[package]
name = "ndsbiosa7"
version = "0.1.0"
edition = "2021"

[profile.release]
opt-level = 'z'
codegen-units = 1
panic = 'abort'
lto = true
strip = true

[dependencies]
opennitro-macros = { git = "https://github.com/OpenNitro-Project/opennitro-macros.git" }