name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install cargo-binutils
      run: cargo install cargo-binutils

    - name: Build A7 BIOS
      run: 
        cargo objcopy --release --verbose -- -O binary ndsa7.bin

    - name: Create artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ndsbiosa7.bin
        path: ./ndsa7.bin
