name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install cargo-binutils
      run: cargo install cargo-binutils

    - name: Build A7 BIOS
      working-directory: ./ndsbiosa7
      run: 
        cargo objcopy --release --verbose -- -O binary ndsa7.bin
